GSRC = ../code/ReadyCRM/src
GBIN = bin
GBUILD = build
GTARGET = $(GBIN)\rdcrm.exe

all: clean qmake compile run

qmake:
	@qmake
compile: $(GOBJS)
	@mingw32-make
clean:
	@if not exist $(GBIN) @mkdir $(GBIN)
	@if not exist $(GBUILD) @mkdir $(GBUILD)
	@del /q $(GBIN)\*
run:
	@$(GTARGET) $(argv)
git_push:
	@cd $(GPROJECT_PATH) && git pull && git add --all && git commit -m "Initial Commit" && git push -u origin main
git_clone:
	@cd $(GPROJECT_ROOT) && git clone $(GGIT_URL) $(GGIT_NAME) 
