#!/bin/bash
#================================================
export "PATH=.:$PATH"
export "PATH=/c/dolibarr/bin/mariadb/mariadb10.4.10/bin:$PATH"
#================================================
export "GPROJECT_ROOT=/c/Users/Admin/Downloads/Programs"
export "GPROJECT_PATH=$GPROJECT_ROOT/ReadyCRM"
export "GDATA_PATH=$GPROJECT_PATH/cpp/win/data"
export "GSQLITE_DB_PATH=$GDATA_PATH/sqlite/config.dat"
export "GSTYLE_PATH=$GDATA_PATH/css/style.css"
export "GFONT_PATH=$GDATA_PATH/font"
export "GIMG_PATH=$GDATA_PATH/img"
export "GPDF_PATH=$GDATA_PATH/pdf/config.pdf"
#================================================
export "GPACMAN_SEARCH=sqlite"
#================================================
export "GGIT_URL=https://github.com/gkesse/ReadyCRM.git"
export "GGIT_NAME=ReadyCRM"
#================================================
export "GMYSQL_HOST=localhost"
export "GMYSQL_PORT=9180"
export "GMYSQL_USER=root"
export "GMYSQL_PASS=admin"
export "GMYSQL_DATABASE=dolibarr"
#================================================
